# All api requests for company endpoint

### Create Company
POST http://localhost:4000/company
Content-Type: application/json

{
    "author": 1233,
    "name":"asd23333",
    "nip": "1231231231",
    "pkd": ["123", "123"]
}

### Update Company
PUT http://localhost:4000/company/3
Content-Type: application/json

{   
    "email":"Klepacze@coś.pl"
}

### Get all Companies
GET http://localhost:4000/company

### Get one company
GET http://localhost:4000/company/2

### Delete company
DELETE http://localhost:4000/company/2



### Upload company file
POST http://localhost:4000/company/upload/1
Content-Type: multipart/form-data; boundary=----FormBoundary

------FormBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< ./test.txt
------FormBoundary--

